# Generated by Django 3.2.4 on 2021-06-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ImageField(default=1, upload_to='hero_image/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='name',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title',
            field=models.TextField(default=1, max_length=200),
        ),
    ]
